#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def CalculaOResto(numero):
    if (numero % 2 == 0):
        return True
    else: 
        return False

def SerieDeFibonacci():
    primeiroValor = 1
    segundoValor = 2
    somaDosImpares = 0
    while (segundoValor < 4000000):
        if(CalculaOResto(segundoValor)):
            somaDosImpares = somaDosImpares + segundoValor
        segundoValor = segundoValor + primeiroValor
        primeiroValor = segundoValor - primeiroValor
    return somaDosImpares

print(SerieDeFibonacci())
